#Indigo properties file
#Mon Aug 10 23:05:08 BST 2026
always-tesselate-blocks=auto
ambient-occlusion-mode=hybrid
fix-smooth-lighting-offset=auto
fix-luminous-block-ambient-occlusion=auto
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
